# Generated by Django 4.2.3 on 2023-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='location',
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_name',
            field=models.CharField(max_length=100),
        ),
    ]
